export const PANEL_CONTROL_DEFINITION = {
    G1000NXI_PFD_DEF: [
        { id: 'btn_vol1knob', action: 'AS1000_PFD_VOL1_KNOB_SELECT', classes: ['knobBase', 'volKnob'], image: './knob_vol.png', left: 60, top: 41, useEncoder: true },
        { id: 'btn_vol2knob', action: 'AS1000_PFD_VOL2_KNOB_SELECT', classes: ['knobBase', 'volKnob'], image: 'knob_vol.png', left: 1296, top: 41, useEncoder: true  },
        { id: 'btn_navknob', action: 'AS1000_PFD_NAV_KNOB_SELECT', classes: ['knobBase', 'regularKnob'], image: 'knob.png', left: 46, top: 171, useDualEncoder: true  },
        { id: 'btn_navswap', action: 'AS1000_PFD_NAV_Switch', classes: ['buttonBase'], image: 'button_swap.png', left: 97, top: 104 },
        { id: 'btn_hdgknob', action: 'AS1000_PFD_HDG_KNOB_SELECT', classes: ['knobBase', 'regularKnob'], image: 'knob_hdg.png', left: 46, top: 338, useDualEncoder: true  },
        { id: 'btn_altknob', action: 'AS1000_PFD_ALT_KNOB_SELECT', classes: ['knobBase', 'regularKnob'], image: 'knob.png', left: 46.5, top: 790, useDualEncoder: true  },
        { id: 'btn_comknob', action: 'AS1000_PFD_COM_KNOB_SELECT', classes: ['knobBase', 'regularKnob'], image: 'knob.png', left: 1282, top: 170, useDualEncoder: true  },
        { id: 'btn_comswap', action: 'AS1000_PFD_COM_Switch', classes: ['buttonBase'], image: 'button_swap.png', left: 1253, top: 104 },
        { id: 'btn_crsknob', action: 'AS1000_PFD_CRS_KNOB_SELECT', classes: ['knobBase', 'crsKnob'], image: 'knob_crs.png', left: 1282, top: 334, useDualEncoder: true  },
        { id: 'btn_rangeknob', action: 'AS1000_PFD_MAP_KNOB_SELECT', classes: ['knobBase', 'rangeKnob'], image: 'knob_range.png', left: 1288, top: 492, useEncoder: true  },
        { id: 'btn_fmsknob', action: 'AS1000_PFD_FMS_KNOB_SELECT', classes: ['knobBase', 'regularKnob'], image: 'knob.png', left: 1281, top: 790, useDualEncoder: true  },

        { id: 'btn_ap', action: 'AP_MASTER', classes: ['buttonBase'], image: 'button_ap.png', left: 22, top: 467 },
        { id: 'btn_hdg', action: 'AP_PANEL_HEADING_HOLD', classes: ['buttonBase'], image: 'button_hdg.png', left: 22, top: 518 },
        { id: 'btn_nav', action: 'AP_NAV1_HOLD', classes: ['buttonBase'], image: 'button_nav.png', left: 22, top: 568 },
        { id: 'btn_apr', action: 'AP_APR_HOLD', classes: ['buttonBase'], image: 'button_apr.png', left: 22, top: 618 },
        { id: 'btn_vs', action: 'AP_VS_HOLD', classes: ['buttonBase'], image: 'button_vs.png', left: 22, top: 668 },
        { id: 'btn_flc', action: 'AS1000_MFD_FLC_Push', classes: ['buttonBase'], image: 'button_flc.png', left: 22, top: 718 },
        { id: 'btn_fd', action: 'TOGGLE_FLIGHT_DIRECTOR', classes: ['buttonBase'], image: 'button_fd.png', left: 94, top: 467 },
        { id: 'btn_alt', action: 'AP_PANEL_ALTITUDE_HOLD', classes: ['buttonBase'], image: 'button_alt.png', left: 94, top: 518 },
        { id: 'btn_vnv', action: 'AS1000_AP_VNAV_Push', classes: ['buttonBase'], image: 'button_vnv.png', left: 94, top: 568 },
        { id: 'btn_bc', action: 'AP_BC_HOLD', classes: ['buttonBase'], image: 'button_bc.png', left: 94, top: 618 },
        { id: 'btn_nose_up', action: 'AS1000_MFD_NOSE_UP', classes: ['buttonBase'], image: 'button_nose_up.png', left: 94, top: 668 },
        { id: 'btn_nose_down', action: 'AS1000_MFD_NOSE_DN', classes: ['buttonBase'], image: 'button_nose_down.png', left: 94, top: 718 },
        { id: 'btn_dir', action: 'AS1000_PFD_DIRECTTO', classes: ['buttonBase'], image: 'button_dir.png', left: 1256, top: 617 },
        { id: 'btn_fpl', action: 'AS1000_PFD_FPL_Push', classes: ['buttonBase'], image: 'button_fpl.png', left: 1256, top: 670 },
        { id: 'btn_clr', action: 'AS1000_PFD_CLR', classes: ['buttonBase'], image: 'button_clr.png', left: 1256, top: 722 },
        { id: 'btn_menu', action: 'AS1000_PFD_MENU_Push', classes: ['buttonBase'], image: 'button_menu.png', left: 1328, top: 617 },
        { id: 'btn_proc', action: 'AS1000_PFD_PROC_Push', classes: ['buttonBase'], image: 'button_proc.png', left: 1328, top: 670 },
        { id: 'btn_ent', action: 'AS1000_PFD_ENT_Push', classes: ['buttonBase'], image: 'button_ent.png', left: 1328, top: 722 },

        { id: 'btn_softkey_1', action: 'AS1000_PFD_SOFTKEYS_1', classes: ['buttonBase'], image: 'button_softkey.png', left: 207, top: 848 },
        { id: 'btn_softkey_2', action: 'AS1000_PFD_SOFTKEYS_2', classes: ['buttonBase'], image: 'button_softkey.png', left: 292, top: 848 },
        { id: 'btn_softkey_3', action: 'AS1000_PFD_SOFTKEYS_3', classes: ['buttonBase'], image: 'button_softkey.png', left: 377, top: 848 },
        { id: 'btn_softkey_4', action: 'AS1000_PFD_SOFTKEYS_4', classes: ['buttonBase'], image: 'button_softkey.png', left: 462, top: 848 },
        { id: 'btn_softkey_5', action: 'AS1000_PFD_SOFTKEYS_5', classes: ['buttonBase'], image: 'button_softkey.png', left: 547, top: 848 },
        { id: 'btn_softkey_6', action: 'AS1000_PFD_SOFTKEYS_6', classes: ['buttonBase'], image: 'button_softkey.png', left: 632, top: 848 },
        { id: 'btn_softkey_7', action: 'AS1000_PFD_SOFTKEYS_7', classes: ['buttonBase'], image: 'button_softkey.png', left: 717, top: 848 },
        { id: 'btn_softkey_8', action: 'AS1000_PFD_SOFTKEYS_8', classes: ['buttonBase'], image: 'button_softkey.png', left: 802, top: 848 },
        { id: 'btn_softkey_9', action: 'AS1000_PFD_SOFTKEYS_9', classes: ['buttonBase'], image: 'button_softkey.png', left: 888, top: 848 },
        { id: 'btn_softkey_10', action: 'AS1000_PFD_SOFTKEYS_10', classes: ['buttonBase'], image: 'button_softkey.png', left: 973, top: 848 },
        { id: 'btn_softkey_11', action: 'AS1000_PFD_SOFTKEYS_11', classes: ['buttonBase'], image: 'button_softkey.png', left: 1058, top: 848 },
        { id: 'btn_softkey_12', action: 'AS1000_PFD_SOFTKEYS_12', classes: ['buttonBase'], image: 'button_softkey.png', left: 1142, top: 848 }
    ],
        
    G1000NXI_MFD_DEF: [
        { id: 'btn_vol1knob', action: 'AS1000_MFD_VOL1_KNOB_SELECT', classes: ['knobBase', 'volKnob'], image: './knob_vol.png', left: 60, top: 41, useEncoder: true },
        { id: 'btn_vol2knob', action: 'AS1000_MFD_VOL2_KNOB_SELECT', classes: ['knobBase', 'volKnob'], image: 'knob_vol.png', left: 1296, top: 41, useEncoder: true  },
        { id: 'btn_navknob', action: 'AS1000_MFD_NAV_KNOB_SELECT', classes: ['knobBase', 'regularKnob'], image: 'knob.png', left: 46, top: 171, useDualEncoder: true  },
        { id: 'btn_navswap', action: 'AS1000_MFD_NAV_Switch', classes: ['buttonBase'], image: 'button_swap.png', left: 97, top: 104 },
        { id: 'btn_hdgknob', action: 'AS1000_MFD_HDG_KNOB_SELECT', classes: ['knobBase', 'regularKnob'], image: 'knob_hdg.png', left: 46, top: 338, useDualEncoder: true  },
        { id: 'btn_altknob', action: 'AS1000_MFD_ALT_KNOB_SELECT', classes: ['knobBase', 'regularKnob'], image: 'knob.png', left: 46.5, top: 790, useDualEncoder: true  },
        { id: 'btn_comknob', action: 'AS1000_MFD_COM_KNOB_SELECT', classes: ['knobBase', 'regularKnob'], image: 'knob.png', left: 1282, top: 170, useDualEncoder: true  },
        { id: 'btn_comswap', action: 'AS1000_MFD_COM_Switch', classes: ['buttonBase'], image: 'button_swap.png', left: 1253, top: 104 },
        { id: 'btn_crsknob', action: 'AS1000_MFD_CRS_KNOB_SELECT', classes: ['knobBase', 'crsKnob'], image: 'knob_crs.png', left: 1282, top: 334, useDualEncoder: true  },
        { id: 'btn_rangeknob', action: 'AS1000_MFD_MAP_KNOB_SELECT', classes: ['knobBase', 'rangeKnob'], image: 'knob_range.png', left: 1288, top: 492, useEncoder: true  },
        { id: 'btn_fmsknob', action: 'AS1000_MFD_FMS_KNOB_SELECT', classes: ['knobBase', 'regularKnob'], image: 'knob.png', left: 1281, top: 790, useDualEncoder: true  },

        { id: 'btn_ap', action: 'AP_MASTER', classes: ['buttonBase'], image: 'button_ap.png', left: 22, top: 467 },
        { id: 'btn_hdg', action: 'AP_PANEL_HEADING_HOLD', classes: ['buttonBase'], image: 'button_hdg.png', left: 22, top: 518 },
        { id: 'btn_nav', action: 'AP_NAV1_HOLD', classes: ['buttonBase'], image: 'button_nav.png', left: 22, top: 568 },
        { id: 'btn_apr', action: 'AP_APR_HOLD', classes: ['buttonBase'], image: 'button_apr.png', left: 22, top: 618 },
        { id: 'btn_vs', action: 'AP_VS_HOLD', classes: ['buttonBase'], image: 'button_vs.png', left: 22, top: 668 },
        { id: 'btn_flc', action: 'AS1000_MFD_FLC_Push', classes: ['buttonBase'], image: 'button_flc.png', left: 22, top: 718 },
        { id: 'btn_fd', action: 'TOGGLE_FLIGHT_DIRECTOR', classes: ['buttonBase'], image: 'button_fd.png', left: 94, top: 467 },
        { id: 'btn_alt', action: 'AP_PANEL_ALTITUDE_HOLD', classes: ['buttonBase'], image: 'button_alt.png', left: 94, top: 518 },
        { id: 'btn_vnv', action: 'AS1000_AP_VNAV_Push', classes: ['buttonBase'], image: 'button_vnv.png', left: 94, top: 568 },
        { id: 'btn_bc', action: 'AP_BC_HOLD', classes: ['buttonBase'], image: 'button_bc.png', left: 94, top: 618 },
        { id: 'btn_nose_up', action: 'AS1000_MFD_NOSE_UP', classes: ['buttonBase'], image: 'button_nose_up.png', left: 94, top: 668 },
        { id: 'btn_nose_down', action: 'AS1000_MFD_NOSE_DN', classes: ['buttonBase'], image: 'button_nose_down.png', left: 94, top: 718 },
        { id: 'btn_dir', action: 'AS1000_MFD_DIRECTTO', classes: ['buttonBase'], image: 'button_dir.png', left: 1256, top: 617 },
        { id: 'btn_fpl', action: 'AS1000_MFD_FPL_Push', classes: ['buttonBase'], image: 'button_fpl.png', left: 1256, top: 670 },
        { id: 'btn_clr', action: 'AS1000_MFD_CLR', classes: ['buttonBase'], image: 'button_clr.png', left: 1256, top: 722 },
        { id: 'btn_menu', action: 'AS1000_MFD_MENU_Push', classes: ['buttonBase'], image: 'button_menu.png', left: 1328, top: 617 },
        { id: 'btn_proc', action: 'AS1000_MFD_PROC_Push', classes: ['buttonBase'], image: 'button_proc.png', left: 1328, top: 670 },
        { id: 'btn_ent', action: 'AS1000_MFD_ENT_Push', classes: ['buttonBase'], image: 'button_ent.png', left: 1328, top: 722 },

        { id: 'btn_softkey_1', action: 'AS1000_MFD_SOFTKEYS_1', classes: ['buttonBase'], image: 'button_softkey.png', left: 207, top: 848 },
        { id: 'btn_softkey_2', action: 'AS1000_MFD_SOFTKEYS_2', classes: ['buttonBase'], image: 'button_softkey.png', left: 292, top: 848 },
        { id: 'btn_softkey_3', action: 'AS1000_MFD_SOFTKEYS_3', classes: ['buttonBase'], image: 'button_softkey.png', left: 377, top: 848 },
        { id: 'btn_softkey_4', action: 'AS1000_MFD_SOFTKEYS_4', classes: ['buttonBase'], image: 'button_softkey.png', left: 462, top: 848 },
        { id: 'btn_softkey_5', action: 'AS1000_MFD_SOFTKEYS_5', classes: ['buttonBase'], image: 'button_softkey.png', left: 547, top: 848 },
        { id: 'btn_softkey_6', action: 'AS1000_MFD_SOFTKEYS_6', classes: ['buttonBase'], image: 'button_softkey.png', left: 632, top: 848 },
        { id: 'btn_softkey_7', action: 'AS1000_MFD_SOFTKEYS_7', classes: ['buttonBase'], image: 'button_softkey.png', left: 717, top: 848 },
        { id: 'btn_softkey_8', action: 'AS1000_MFD_SOFTKEYS_8', classes: ['buttonBase'], image: 'button_softkey.png', left: 802, top: 848 },
        { id: 'btn_softkey_9', action: 'AS1000_MFD_SOFTKEYS_9', classes: ['buttonBase'], image: 'button_softkey.png', left: 888, top: 848 },
        { id: 'btn_softkey_10', action: 'AS1000_MFD_SOFTKEYS_10', classes: ['buttonBase'], image: 'button_softkey.png', left: 973, top: 848 },
        { id: 'btn_softkey_11', action: 'AS1000_MFD_SOFTKEYS_11', classes: ['buttonBase'], image: 'button_softkey.png', left: 1058, top: 848 },
        { id: 'btn_softkey_12', action: 'AS1000_MFD_SOFTKEYS_12', classes: ['buttonBase'], image: 'button_softkey.png', left: 1142, top: 848 }
    ],

    FBWA32NX_CDU_DEF: [
        { id: 'btn_selectleft1', action: 'A320_Neo_CDU_1_BTN_L1', classes: ['selectButtonBase'], image: 'cdu/button_select.png', left: 14, top: 89 },
        { id: 'btn_selectleft2', action: 'A320_Neo_CDU_1_BTN_L2', classes: ['selectButtonBase'], image: 'cdu/button_select.png', left: 14, top: 125 },
        { id: 'btn_selectleft3', action: 'A320_Neo_CDU_1_BTN_L3', classes: ['selectButtonBase'], image: 'cdu/button_select.png', left: 14, top: 161 },
        { id: 'btn_selectleft4', action: 'A320_Neo_CDU_1_BTN_L4', classes: ['selectButtonBase'], image: 'cdu/button_select.png', left: 14, top: 196 },
        { id: 'btn_selectleft5', action: 'A320_Neo_CDU_1_BTN_L5', classes: ['selectButtonBase'], image: 'cdu/button_select.png', left: 14, top: 231 },
        { id: 'btn_selectleft6', action: 'A320_Neo_CDU_1_BTN_L6', classes: ['selectButtonBase'], image: 'cdu/button_select.png', left: 14, top: 268 },
        { id: 'btn_selectright1', action: 'A320_Neo_CDU_1_BTN_R1', classes: ['selectButtonBase'], image: 'cdu/button_select.png', left: 401, top: 89 },
        { id: 'btn_selectright2', action: 'A320_Neo_CDU_1_BTN_R2', classes: ['selectButtonBase'], image: 'cdu/button_select.png', left: 401, top: 125 },
        { id: 'btn_selectright3', action: 'A320_Neo_CDU_1_BTN_R3', classes: ['selectButtonBase'], image: 'cdu/button_select.png', left: 401, top: 161 },
        { id: 'btn_selectright4', action: 'A320_Neo_CDU_1_BTN_R4', classes: ['selectButtonBase'], image: 'cdu/button_select.png', left: 401, top: 196 },
        { id: 'btn_selectright5', action: 'A320_Neo_CDU_1_BTN_R5', classes: ['selectButtonBase'], image: 'cdu/button_select.png', left: 401, top: 231 },
        { id: 'btn_selectright6', action: 'A320_Neo_CDU_1_BTN_R6', classes: ['selectButtonBase'], image: 'cdu/button_select.png', left: 401, top: 268 },

        { id: 'btn_dir', action: 'A320_Neo_CDU_1_BTN_DIR', classes: ['rectangleButtonBase'], image: 'cdu/button_dir.png', left: 53, top: 329 },
        { id: 'btn_prog', action: 'A320_Neo_CDU_1_BTN_PROG', classes: ['rectangleButtonBase'], image: 'cdu/button_prog.png', left: 103, top: 329 },
        { id: 'btn_perf', action: 'A320_Neo_CDU_1_BTN_PERF', classes: ['rectangleButtonBase'], image: 'cdu/button_perf.png', left: 153, top: 329 },
        { id: 'btn_init', action: 'A320_Neo_CDU_1_BTN_INIT', classes: ['rectangleButtonBase'], image: 'cdu/button_int.png', left: 203, top: 329 },
        { id: 'btn_data', action: 'A320_Neo_CDU_1_BTN_DATA', classes: ['rectangleButtonBase'], image: 'cdu/button_data.png', left: 253, top: 329 },
        { id: 'btn_blank1', action: null, classes: ['rectangleButtonBase'], image: 'cdu/button_blank.png', left: 303, top: 329 },
        { id: 'btn_fpln', action: 'A320_Neo_CDU_1_BTN_FPLN', classes: ['rectangleButtonBase'], image: 'cdu/button_fpln.png', left: 53, top: 363 },
        { id: 'btn_radnav', action: 'A320_Neo_CDU_1_BTN_RAD', classes: ['rectangleButtonBase'], image: 'cdu/button_radnav.png', left: 103, top: 363 },
        { id: 'btn_fuelpred', action: 'A320_Neo_CDU_1_BTN_FUEL', classes: ['rectangleButtonBase'], image: 'cdu/button_fuelpred.png', left: 153, top: 363 },
        { id: 'btn_secfpln', action: 'A320_Neo_CDU_1_BTN_SEC', classes: ['rectangleButtonBase'], image: 'cdu/button_secfpln.png', left: 203, top: 363 },
        { id: 'btn_atcomm', action: 'A320_Neo_CDU_1_BTN_ATC', classes: ['rectangleButtonBase'], image: 'cdu/button_atccomm.png', left: 253, top: 363 },
        { id: 'btn_mcdumenu', action: 'A320_Neo_CDU_1_BTN_MENU', classes: ['rectangleButtonBase'], image: 'cdu/button_mcdumenu.png', left: 303, top: 363 },
        { id: 'btn_airport', action: 'A320_Neo_CDU_1_BTN_AIRPORT', classes: ['rectangleButtonBase'], image: 'cdu/button_airport.png', left: 53, top: 400 },
        { id: 'btn_blank2', action: null, classes: ['rectangleButtonBase'], image: 'cdu/button_blank.png', left: 103, top: 400 },
        { id: 'btn_arrowleft', action: 'A320_Neo_CDU_1_BTN_PREVPAGE', classes: ['rectangleButtonBase'], image: 'cdu/button_arrowleft.png', left: 53, top: 437 },
        { id: 'btn_arrowright', action: 'A320_Neo_CDU_1_BTN_NEXTPAGE', classes: ['rectangleButtonBase'], image: 'cdu/button_arrowright.png', left: 53, top: 474 },
        { id: 'btn_arrowup', action: 'A320_Neo_CDU_1_BTN_UP', classes: ['rectangleButtonBase'], image: 'cdu/button_arrowup.png', left: 103, top: 437 },
        { id: 'btn_arrowdown', action: 'A320_Neo_CDU_1_BTN_DOWN', classes: ['rectangleButtonBase'], image: 'cdu/button_arrowdown.png', left: 103, top: 474 },
        { id: 'btn_bright', action: null, classes: ['brightdimButtonBase'], image: 'cdu/button_bright.png', left: 368, top: 327 },
        { id: 'btn_dim', action: null, classes: ['brightdimButtonBase'], image: 'cdu/button_dim.png', left: 368, top: 363 },

        { id: 'btn_1', action: 'A320_Neo_CDU_1_BTN_1', classes: ['squareButtonBase'], image: 'cdu/button_1.png', left: 53, top: 521 },
        { id: 'btn_2', action: 'A320_Neo_CDU_1_BTN_2', classes: ['squareButtonBase'], image: 'cdu/button_2.png', left: 99, top: 521 },
        { id: 'btn_3', action: 'A320_Neo_CDU_1_BTN_3', classes: ['squareButtonBase'], image: 'cdu/button_3.png', left: 142, top: 521 },
        { id: 'btn_4', action: 'A320_Neo_CDU_1_BTN_4', classes: ['squareButtonBase'], image: 'cdu/button_4.png', left: 53, top: 556 },
        { id: 'btn_5', action: 'A320_Neo_CDU_1_BTN_5', classes: ['squareButtonBase'], image: 'cdu/button_5.png', left: 99, top: 556 },
        { id: 'btn_6', action: 'A320_Neo_CDU_1_BTN_6', classes: ['squareButtonBase'], image: 'cdu/button_6.png', left: 142, top: 556 },
        { id: 'btn_7', action: 'A320_Neo_CDU_1_BTN_7', classes: ['squareButtonBase'], image: 'cdu/button_7.png', left: 53, top: 591 },
        { id: 'btn_8', action: 'A320_Neo_CDU_1_BTN_8', classes: ['squareButtonBase'], image: 'cdu/button_8.png', left: 99, top: 591 },
        { id: 'btn_9', action: 'A320_Neo_CDU_1_BTN_9', classes: ['squareButtonBase'], image: 'cdu/button_9.png', left: 142, top: 591 },
        { id: 'btn_dot', action: 'A320_Neo_CDU_1_BTN_DOT', classes: ['squareButtonBase'], image: 'cdu/button_period.png', left: 53, top: 624 },
        { id: 'btn_0', action: 'A320_Neo_CDU_1_BTN_0', classes: ['squareButtonBase'], image: 'cdu/button_0.png', left: 99, top: 624 },
        { id: 'btn_plusminus', action: 'A320_Neo_CDU_1_BTN_PLUSMINUS', classes: ['squareButtonBase'], image: 'cdu/button_plusminus.png', left: 142, top: 624 },

        { id: 'btn_a', action: 'A320_Neo_CDU_1_BTN_A', classes: ['squareButtonBase'], image: 'cdu/button_a.png', left: 186, top: 420 },
        { id: 'btn_b', action: 'A320_Neo_CDU_1_BTN_B', classes: ['squareButtonBase'], image: 'cdu/button_b.png', left: 228, top: 420 },
        { id: 'btn_c', action: 'A320_Neo_CDU_1_BTN_C', classes: ['squareButtonBase'], image: 'cdu/button_c.png', left: 271, top: 420 },
        { id: 'btn_d', action: 'A320_Neo_CDU_1_BTN_D', classes: ['squareButtonBase'], image: 'cdu/button_d.png', left: 313, top: 420 },
        { id: 'btn_e', action: 'A320_Neo_CDU_1_BTN_E', classes: ['squareButtonBase'], image: 'cdu/button_e.png', left: 356, top: 420 },
        { id: 'btn_f', action: 'A320_Neo_CDU_1_BTN_F', classes: ['squareButtonBase'], image: 'cdu/button_f.png', left: 186, top: 461 },
        { id: 'btn_g', action: 'A320_Neo_CDU_1_BTN_G', classes: ['squareButtonBase'], image: 'cdu/button_g.png', left: 228, top: 461 },
        { id: 'btn_h', action: 'A320_Neo_CDU_1_BTN_H', classes: ['squareButtonBase'], image: 'cdu/button_h.png', left: 271, top: 461 },
        { id: 'btn_i', action: 'A320_Neo_CDU_1_BTN_I', classes: ['squareButtonBase'], image: 'cdu/button_i.png', left: 313, top: 461 },
        { id: 'btn_j', action: 'A320_Neo_CDU_1_BTN_J', classes: ['squareButtonBase'], image: 'cdu/button_j.png', left: 356, top: 461 },
        { id: 'btn_k', action: 'A320_Neo_CDU_1_BTN_K', classes: ['squareButtonBase'], image: 'cdu/button_k.png', left: 186, top: 502 },
        { id: 'btn_l', action: 'A320_Neo_CDU_1_BTN_L', classes: ['squareButtonBase'], image: 'cdu/button_l.png', left: 228, top: 502 },
        { id: 'btn_m', action: 'A320_Neo_CDU_1_BTN_M', classes: ['squareButtonBase'], image: 'cdu/button_m.png', left: 271, top: 502 },
        { id: 'btn_n', action: 'A320_Neo_CDU_1_BTN_N', classes: ['squareButtonBase'], image: 'cdu/button_n.png', left: 313, top: 502 },
        { id: 'btn_o', action: 'A320_Neo_CDU_1_BTN_O', classes: ['squareButtonBase'], image: 'cdu/button_o.png', left: 356, top: 502 },
        { id: 'btn_p', action: 'A320_Neo_CDU_1_BTN_P', classes: ['squareButtonBase'], image: 'cdu/button_p.png', left: 186, top: 543 },
        { id: 'btn_q', action: 'A320_Neo_CDU_1_BTN_Q', classes: ['squareButtonBase'], image: 'cdu/button_q.png', left: 228, top: 543 },
        { id: 'btn_r', action: 'A320_Neo_CDU_1_BTN_R', classes: ['squareButtonBase'], image: 'cdu/button_r.png', left: 271, top: 543 },
        { id: 'btn_s', action: 'A320_Neo_CDU_1_BTN_S', classes: ['squareButtonBase'], image: 'cdu/button_s.png', left: 313, top: 543 },
        { id: 'btn_t', action: 'A320_Neo_CDU_1_BTN_T', classes: ['squareButtonBase'], image: 'cdu/button_t.png', left: 356, top: 543 },
        { id: 'btn_u', action: 'A320_Neo_CDU_1_BTN_U', classes: ['squareButtonBase'], image: 'cdu/button_u.png', left: 186, top: 583 },
        { id: 'btn_v', action: 'A320_Neo_CDU_1_BTN_V', classes: ['squareButtonBase'], image: 'cdu/button_v.png', left: 228, top: 583 },
        { id: 'btn_w', action: 'A320_Neo_CDU_1_BTN_W', classes: ['squareButtonBase'], image: 'cdu/button_w.png', left: 271, top: 583 },
        { id: 'btn_x', action: 'A320_Neo_CDU_1_BTN_X', classes: ['squareButtonBase'], image: 'cdu/button_x.png', left: 313, top: 583 },
        { id: 'btn_y', action: 'A320_Neo_CDU_1_BTN_Y', classes: ['squareButtonBase'], image: 'cdu/button_y.png', left: 356, top: 583 },
        { id: 'btn_z', action: 'A320_Neo_CDU_1_BTN_Z', classes: ['squareButtonBase'], image: 'cdu/button_z.png', left: 186, top: 623 },
        { id: 'btn_slash', action: 'A320_Neo_CDU_1_BTN_DIV', classes: ['squareButtonBase'], image: 'cdu/button_slash.png', left: 228, top: 623 },
        { id: 'btn_sp', action: 'A320_Neo_CDU_1_BTN_SP', classes: ['squareButtonBase'], image: 'cdu/button_sp.png', left: 271, top: 623 },
        { id: 'btn_ovfy', action: 'A320_Neo_CDU_1_BTN_OVFY', classes: ['squareButtonBase'], image: 'cdu/button_ovfy.png', left: 313, top: 623 },
        { id: 'btn_clr', action: 'A320_Neo_CDU_1_BTN_CLR', classes: ['squareButtonBase'], image: 'cdu/button_clr.png', left: 356, top: 623 } 
    ]
}